# Generated by Django 3.0.6 on 2020-06-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200620_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='text',
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Post'),
        ),
    ]
