# Generated by Django 3.0.6 on 2020-06-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_podrobnee',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
