# Generated by Django 3.0.6 on 2020-06-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200620_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_podrobnee',
        ),
    ]
